version: '3.3'
services:
  database-service:
      build: database-service
      environment:
        - POSTGRES_PASSWORD=secret
      ports:
        - 5432:5432
      volumes:
        - ./blockstorage/postgres:/var/lib/postgresql/data
  usuarios:
    image: admin_usuarios:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    depends_on:
      - database-service
 
  publicaciones:
    image: publicaciones:0.0.1-SNAPSHOT
    ports:
      - 8082:8082
    depends_on:
      - database-service
  discovery-server:
    image: discovery_server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  monitoring-server:
    image: server-metrics:0.0.1-SNAPSHOT
    ports:
      - 8086:8086
  
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"