version: '3.3'
services:
  database-service:
      build: database-service
      environment:
        - POSTGRES_PASSWORD=secret
      ports:
        - 5432:5432
      volumes:
        - ./blockstorage/postgres:/var/lib/postgresql/data
  discovery-server:
    image: discovery_server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  usuarios:
    image: admin_usuarios:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    depends_on:
      - database-service
  publicaciones:
    image: publicaciones:0.0.1-SNAPSHOT
    ports:
      - 8082:8082
    depends_on:
      - database-service