version: '3.3'

networks:
    red-social:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: 192.168.2.0/24

services:
  database-service:
    build: database-service
    image: angelsantander/database-service:0.1
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/data
    networks:
      red-social:
        ipv4_address: 192.168.2.10
    container_name: database
  usuarios:
    image: angelsantander/admin_usuarios:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    depends_on:
      - database-service
    networks:
      red-social:
        ipv4_address: 192.168.2.2
    container_name: usuarios
 
  publicaciones:
    image: angelsantander/publicaciones:0.0.1-SNAPSHOT
    ports:
      - 8082:8082
    depends_on:
      - database-service
    networks:
      red-social:
        ipv4_address: 192.168.2.3
    container_name: publicaciones

  seguidores:
    image: angelsantander/seguidores:0.0.1-SNAPSHOT
    ports:
      - 8083:8083
    depends_on:
      - database-service
    networks:
      red-social:
        ipv4_address: 192.168.2.4
    container_name: seguidores

  comentarios:
    image: angelsantander/comentarios:0.0.1-SNAPSHOT
    ports:
      - 8084:8084
    depends_on:
      - database-service
    networks:
      red-social:
        ipv4_address: 192.168.2.5
    container_name: comentarios
  
  mensajes:
    image: angelsantander/mensajes:0.0.1-SNAPSHOT
    ports:
      - 8085:8085
    depends_on:
      - database-service
    networks:
      red-social:
        ipv4_address: 192.168.2.6
    container_name: mensajes

  discovery-server:
    image: angelsantander/discovery_server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      red-social:
        ipv4_address: 192.168.2.7
  
  monitoring-server:
    image: angelsantander/server-metrics:0.0.1-SNAPSHOT
    ports:
      - 8086:8086
    networks:
      red-social:
        ipv4_address: 192.168.2.8
  
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      red-social:
        ipv4_address: 192.168.2.9