version: '3.3'

networks:
  red-micro-servicio:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

services:
  database-service:
    build: database-service
    image: angelsantander/database-service:0.1
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/data
    networks:
      red-micro-servicio:
        ipv4_address: 192.168.2.7
  micro:
    image: angelsantander/${micro}:0.0.1-SNAPSHOT
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - database-service
    networks:
      red-micro-servicio:
        ipv4_address: 192.168.2.2
  discovery-server:
    image: angelsantander/discovery_server:0.0.1-SNAPSHOT
    ports:
      - 127.0.0.1:8761:8761
    networks:
      red-micro-servicio:
        ipv4_address: 192.168.2.3
  monitoring-server:
    image: angelsantander/server-metrics:0.0.1-SNAPSHOT
    ports:
      - 127.0.0.1:8086:8086
    networks:
      red-micro-servicio:
        ipv4_address: 192.168.2.4
  
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    networks:
      red-micro-servicio:
        ipv4_address: 192.168.2.5