
CREATE TABLE public.comentario (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	contenido varchar(255) NULL,
	datetime varchar(255) NULL,
	id_publicacion int4 NULL,
	id_usuario int4 NULL,
	CONSTRAINT comentario_pkey PRIMARY KEY (id)
);

insert into comentario(contenido,id_publicacion,id_usuario,"datetime")
values
('jaja que chistoso',1,1,to_char(now(),'yyyy-MM-dd HH:mm:ss')),
('saludos',2,1,to_char(now(),'yyyy-MM-dd HH:mm:ss')),
('xd',1,2,to_char(now(),'yyyy-MM-dd HH:mm:ss')),
('salu2 a la familia',2,1,to_char(now(),'yyyy-MM-dd HH:mm:ss'));