/* create table user_token(
	id int primary key,
	token varchar(64)
); */

CREATE TABLE public.usuarios (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	contrasenia varchar(255) NULL,
	correo varchar(255) NULL,
	materno varchar(255) NULL,
	nombre varchar(255) NULL,
	paterno varchar(255) NULL,
	CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

insert into usuarios(contrasenia, correo, nombre, paterno,  materno)
VALUES('5520','angelsantander609@gmail.com','Angel','Santander','Martinez'),
('5521','angelsantander2@gmail.com','Angel 2','Santander 2','Martinez 2');